name: media_kit_video_controls
description: Default video controls for package:media_kit.
homepage: https://github.com/alexmercerind/media_kit
repository: https://github.com/alexmercerind/media_kit
version: 0.0.1
funding:
  - https://www.github.com/sponsors/alexmercerind

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  # NOTE: Bump before publishing to pub.dev.
  media_kit: ^0.0.4
  # NOTE: Bump before publishing to pub.dev.
  media_kit_video: ^0.0.4
  # provider: ^6.0.3
  wakelock: ^0.6.2
  window_manager: ^0.3.2
dev_dependencies:
  flutter_lints: ^2.0.0

dependency_overrides:
  # NOTE: Remove before publishing to pub.dev.
  media_kit:
    path: ../media_kit
  # NOTE: Remove before publishing to pub.dev.
  media_kit_video:
    path: ../media_kit_video
